---
users:

  'plone':
    name: 'Plone installation'
    email: 'jeff.bledsoe@pretagov.com.au'
    public_keys: []
    state: present
    shell: '/bin/bash'
    groups:
      - 'docker'
      - 'plone'
